### ISSUE TITLE
Нарушена логика коннекта клиента.

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/EpicMorg-Supervisor#5]
Как сейчас:
* Коннектиться можно анонимно к любому серверу. Брутфорсом ip и порта. WUT!?

Как нужно:
* Коннектиться по ip:порт и паролю. Как это реализовано в админ-панеле.

**Comment by stamepicmorg** [comment]
EpicMorg-Supervisor/issues/3

**Comment by Smirnyga** [comment]
разобрались. в текущей реализации так и задумано.

сделаем пометку на будущее, если вдруг реализацию будем менять.
